# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8HbRQCesDfJGYJlYNCqv95LDuwQK1XO
"""

print("heee")